### ISSUE TITLE
GreatExpectationsBigQueryOperator is failing on Airflow

### ISSUE THREAD

**Issue by marktanios7** [great-expectations/airflow-provider-great-expectations#14]
**Describe the bug**
Hi,
I have deployed Great Expectations with Google Cloud Composer. I've created an Airflow DAG to insert data into table from another table and then validate if the data is correct. Then I generated suite file using the [scaffold example](https://docs.greatexpectations.io/en/stable/guides/how_to_guides/creating_and_editing_expectations/how_to_create_a_new_expectation_suite_using_suite_scaffold.html). I added all of GE files to GCP bucket. But I'm receiving this error: `DataContextError: No validation operator 'action_list_operator' was found in your project. Please verify this in your great_expectations.yml`. I'm sure that `action_list_operator` exists in my `great_expectations.yml` file.

**Error message:**
`DataContextError: No validation operator 'action_list_operator' was found in your project. Please verify this in your great_expectations.yml`. I'm sure that `action_list_operator` exists in my `great_expectations.yml` file.

**How to reproduce:**
1.  Installed `pybigquery`, `great_expectations`, `airflow-provider-great-expectations` on the composer environment.
2. Followed this [example](https://github.com/great-expectations/airflow-provider-great-expectations/tree/main/great_expectations_provider/examples) with the same folder structure.

**Environment Versions:**
Airflow Version: 1.10.9+composer
Great Expectations Version: 0.13.11

I've also attached my `DAG` and `great_expectations`.yml files.

**Workaround:**
One workaround to fix this is that I've created my custom operator using this [code](https://github.com/great-expectations/airflow-provider-great-expectations/blob/main/great_expectations_provider/operators/great_expectations_bigquery.py) and added `action_list_operator` part manually inside `create_data_context_config` function. But I'm receiving another error: `IndexError: tuple index out of range`

**Workaround Error:**
![image](https://user-images.githubusercontent.com/76472085/110331840-48998580-8028-11eb-8123-c168809ec7eb.png)

[attached_files.zip](https://github.com/great-expectations/airflow-provider-great-expectations/files/6101967/attached_files.zip)

Thanks in advance!

**Comment by spbail** [comment]
Thanks for filing this issue! We're looking into this, there have recently been changes to the Checkpoint/Validation Operator functionality in core Great Expectations, so the operator needs to be adapted for that.
