### ISSUE TITLE
Error initializing a Checkpoint using CheckpointConfig

### ISSUE THREAD

**Issue by dbarrundiag** [great-expectations/airflow-provider-great-expectations#43]
In `great_expectations==0.14.4` the `Checkpoint` class does not have a `module_name` class attribute (https://github.com/great-expectations/great_expectations/blob/0.14.4/great_expectations/checkpoint/checkpoint.py#L74) however when initializing a `Checkpoint` on the Great Expectations Operator (https://github.com/great-expectations/airflow-provider-great-expectations/blob/main/great_expectations_provider/operators/great_expectations.py#L139) a `Checkpoint` is initialized with all the attributes of `checkpoint_config.to_json_dict()` but the CheckpointConfig has a `module_name` attribute so this causes an error when initializing the Checkpoint.

Stack Trace
```
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/great_expectations_provider/operators/great_expectations.py", line 139, in __init__
    data_context=self.data_context, **self.checkpoint_config.to_json_dict()
TypeError: __init__() got an unexpected keyword argument 'module_name'
```

**Comment by talagluck** [comment]
Thanks for opening this! Resolved by #44
