### ISSUE TITLE
GreatExpectationsOperator Performance Issue

### ISSUE THREAD

**Issue by denimalpaca** [great-expectations/airflow-provider-great-expectations#45]
**Is your feature request related to a problem? Please describe.**
The `GreatExpectationsOperator` for Airflow currently instantiates a DataContext in the `__init__()` method, which gets run every time the task is parsed (which is frequently), slowing down the DAG it is a part of.

**Describe the solution you'd like**
Move instantiation of DataContext and Checkpoint to the `execute()` method of the Operator.

I will open a PR on this shortly, feel free to assign to me.

**Comment by dbarrundiag** [comment]
+1

It took me a while to figure this one out! @denimalpaca - you beat me in creating this issue by ~1hr 😆 

To add more details, the instantiation of DataContext can take more than 30 seconds, and the default DAG BAG timeout is 30 seconds (https://airflow.apache.org/docs/apache-airflow/2.2.0/configurations-ref.html#dagbag-import-timeout), so using this Operator inside a DAG can break the parsing of the DAG.

**Comment by denimalpaca** [comment]
Hey @dbarrundiag, I have the PR open [here](https://github.com/great-expectations/airflow-provider-great-expectations/pull/46) if you'd like to check it out. I tested it in my local environment and it seems to work just fine.
