### ISSUE TITLE
Use Airflow's S3 (and others) connections

### ISSUE THREAD

**Issue by Casyfill** [great-expectations/airflow-provider-great-expectations#8]
Use proper Airflow's s3 hooks, rather than default configuration, while running GE.
(have code, will PR asap)

**Comment by spbail** [comment]
Closing this issue - see suggested solution on the PR comments: Since we may have a multitude of connections to handle, it makes more sense to handle that in a subclass of the operator (like the BigQueryOperator).

**Comment by Casyfill** [comment]
Sounds good.
